{% set name = "fx-gltf" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/jessey-git/fx-gltf/archive/v{{ version }}.tar.gz
    sha256: d044d191f9f6c956bdbaf548d960ae9831fd13dfdc4c82fceefa90cb02a68091
    patches:
      - exclude-apple-from-stdc++fs-linking.patch
  - url: https://github.com/KhronosGroup/glTF-Sample-Models/archive/2279f7a96e64f76c8bfb306b3b8fd666b2bb93bf.zip
    sha256: be28a164e548775d94f15abd19ec71ca4c22e9e2d66f27757fbab412838360f0
    folder: test/data/glTF-Sample-Models

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - catch2 >=2.6,<3.0
    - cmake
    - ninja
  host:
    - nlohmann_json

test:
  commands:
    - test -f $PREFIX/lib/cmake/fx-gltf/fx-gltfConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\fx-gltf\\fx-gltfConfig.cmake exit 1  # [win]

about:
  home: https://github.com/jessey-git/fx-gltf
  summary: 'A C++14/C++17 header-only library for simple, efficient, and robust serialization/deserialization of glTF 2.0'
  description: |
    A C++14/C++17 header-only library for simple, efficient, and robust serialization/deserialization of glTF 2.0.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/jessey-git/fx-gltf

extra:
  recipe-maintainers:
    - jeongseok-meta
